/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ObrigadoOrderIdRouteImport } from './routes/obrigado.$orderId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutPublicIdRouteImport } from './routes/checkout.$publicId'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppProdutosIndexRouteImport } from './routes/app.produtos.index'
import { Route as AppCheckoutsIndexRouteImport } from './routes/app.checkouts.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppProdutosIdRouteImport } from './routes/app.produtos.$id'
import { Route as AppCheckoutsIdRouteImport } from './routes/app.checkouts.$id'
import { Route as ApiPublicAbacateWebhookRouteImport } from './routes/api/public/abacate-webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ObrigadoOrderIdRoute = ObrigadoOrderIdRouteImport.update({
  id: '/obrigado/$orderId',
  path: '/obrigado/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPublicIdRoute = CheckoutPublicIdRouteImport.update({
  id: '/checkout/$publicId',
  path: '/checkout/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosIndexRoute = AppProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutsIndexRoute = AppCheckoutsIndexRouteImport.update({
  id: '/checkouts/',
  path: '/checkouts/',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProdutosIdRoute = AppProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutsIdRoute = AppCheckoutsIdRouteImport.update({
  id: '/checkouts/$id',
  path: '/checkouts/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicAbacateWebhookRoute = ApiPublicAbacateWebhookRouteImport.update({
  id: '/api/public/abacate-webhook',
  path: '/api/public/abacate-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/checkout/$publicId': typeof CheckoutPublicIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/obrigado/$orderId': typeof ObrigadoOrderIdRoute
  '/app/': typeof AppIndexRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/app/checkouts/$id': typeof AppCheckoutsIdRoute
  '/app/produtos/$id': typeof AppProdutosIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/checkouts/': typeof AppCheckoutsIndexRoute
  '/app/produtos/': typeof AppProdutosIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/checkout/$publicId': typeof CheckoutPublicIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/obrigado/$orderId': typeof ObrigadoOrderIdRoute
  '/app': typeof AppIndexRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/app/checkouts/$id': typeof AppCheckoutsIdRoute
  '/app/produtos/$id': typeof AppProdutosIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/checkouts': typeof AppCheckoutsIndexRoute
  '/app/produtos': typeof AppProdutosIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/checkout/$publicId': typeof CheckoutPublicIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/obrigado/$orderId': typeof ObrigadoOrderIdRoute
  '/app/': typeof AppIndexRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/app/checkouts/$id': typeof AppCheckoutsIdRoute
  '/app/produtos/$id': typeof AppProdutosIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/checkouts/': typeof AppCheckoutsIndexRoute
  '/app/produtos/': typeof AppProdutosIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/pedidos'
    | '/app/vendas'
    | '/app/webhooks'
    | '/checkout/$publicId'
    | '/email/unsubscribe'
    | '/obrigado/$orderId'
    | '/app/'
    | '/api/public/abacate-webhook'
    | '/app/checkouts/$id'
    | '/app/produtos/$id'
    | '/lovable/email/suppression'
    | '/app/checkouts/'
    | '/app/produtos/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/pedidos'
    | '/app/vendas'
    | '/app/webhooks'
    | '/checkout/$publicId'
    | '/email/unsubscribe'
    | '/obrigado/$orderId'
    | '/app'
    | '/api/public/abacate-webhook'
    | '/app/checkouts/$id'
    | '/app/produtos/$id'
    | '/lovable/email/suppression'
    | '/app/checkouts'
    | '/app/produtos'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/pedidos'
    | '/app/vendas'
    | '/app/webhooks'
    | '/checkout/$publicId'
    | '/email/unsubscribe'
    | '/obrigado/$orderId'
    | '/app/'
    | '/api/public/abacate-webhook'
    | '/app/checkouts/$id'
    | '/app/produtos/$id'
    | '/lovable/email/suppression'
    | '/app/checkouts/'
    | '/app/produtos/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CheckoutPublicIdRoute: typeof CheckoutPublicIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ObrigadoOrderIdRoute: typeof ObrigadoOrderIdRoute
  ApiPublicAbacateWebhookRoute: typeof ApiPublicAbacateWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/obrigado/$orderId': {
      id: '/obrigado/$orderId'
      path: '/obrigado/$orderId'
      fullPath: '/obrigado/$orderId'
      preLoaderRoute: typeof ObrigadoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$publicId': {
      id: '/checkout/$publicId'
      path: '/checkout/$publicId'
      fullPath: '/checkout/$publicId'
      preLoaderRoute: typeof CheckoutPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos/': {
      id: '/app/produtos/'
      path: '/produtos'
      fullPath: '/app/produtos/'
      preLoaderRoute: typeof AppProdutosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkouts/': {
      id: '/app/checkouts/'
      path: '/checkouts'
      fullPath: '/app/checkouts/'
      preLoaderRoute: typeof AppCheckoutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/produtos/$id': {
      id: '/app/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/app/produtos/$id'
      preLoaderRoute: typeof AppProdutosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkouts/$id': {
      id: '/app/checkouts/$id'
      path: '/checkouts/$id'
      fullPath: '/app/checkouts/$id'
      preLoaderRoute: typeof AppCheckoutsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/abacate-webhook': {
      id: '/api/public/abacate-webhook'
      path: '/api/public/abacate-webhook'
      fullPath: '/api/public/abacate-webhook'
      preLoaderRoute: typeof ApiPublicAbacateWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCheckoutsIdRoute: typeof AppCheckoutsIdRoute
  AppProdutosIdRoute: typeof AppProdutosIdRoute
  AppCheckoutsIndexRoute: typeof AppCheckoutsIndexRoute
  AppProdutosIndexRoute: typeof AppProdutosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppVendasRoute: AppVendasRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppCheckoutsIdRoute: AppCheckoutsIdRoute,
  AppProdutosIdRoute: AppProdutosIdRoute,
  AppCheckoutsIndexRoute: AppCheckoutsIndexRoute,
  AppProdutosIndexRoute: AppProdutosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CheckoutPublicIdRoute: CheckoutPublicIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ObrigadoOrderIdRoute: ObrigadoOrderIdRoute,
  ApiPublicAbacateWebhookRoute: ApiPublicAbacateWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
